<template>
    <FloatingPanel
        :left="800"
        :top="200"
        title="代码"
        :width="1000"
        background-color="black"
    >
        <pre class="code">{{showingCode}}</pre>
    </FloatingPanel>
</template>

<script>
import FloatingPanel from "@/components/FloatingPanel";
export default {
    name: "PanelCode",
    components: {FloatingPanel},

    data(){
        return {
            showingCode: '',
            codeOrigin: `yarn install v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
ready:    [ ================================================================================= 100% ]
combile:  [ ================================================================================= 100% ]
finished: [ ================================================================================= 100% ]
warning @vue/cli-plugin-babel > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 20.11s.`,
            offset: 0, // 当前显示代码的位置
            step: 2, // 一次移动几个字符
            intervalHandle: null,
            interval: 60, // ms
        }
    },
    mounted() {
        this.intervalHandle = setInterval(()=> {
            if (this.showingCode === this.codeOrigin){
                this.showingCode = ''
                this.offset = 0
                // this.clearInterval()
            } else {
                this.showingCode = this.codeOrigin.substring(0, this.offset)
                this.offset = this.offset + this.step
            }
        }, this.interval)
    },
    methods: {
        clearInterval(){
            if (this.intervalHandle) clearInterval(this.intervalHandle)
        }
    },
    beforeUnmount() {
        this.clearInterval()
    }
}
</script>

<style scoped lang="scss">
@import "src/assets/scss/plugin";
.code{
    white-space: break-spaces;
    color: white;
    font-weight: bold;
    height: 600px;
}

</style>
