<template>
    <FloatingPanel
        :left="850"
        :top="120"
        title="代码"
        :width="1000"
        background-color="black"
        animate-in-class="animate__fadeInRight"
    >
        <pre class="code">{{showingCode}}</pre>
    </FloatingPanel>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import FloatingPanel from "@/components/FloatingPanel.vue"
import LaunchButton from "@/components/LaunnchButton.vue"

// Reactive data
const showingCode = ref('')
// ASCII 颜文字生成可以去这个网站： https://patorjk.com/software/taag/#p=display&h=1&f=Doom&t=Kyle%20Bing
const codeOrigin = `SCRIPT INIT v1.13.67
SYSTEM IS BOOTING, PLEASE HOLD ...

  ,            _         , __
 /|   /       | |       /|/  \\o
  |__/        | |  _     | __/    _  _    __,
  | \\   |   | |/  |/     |   \\|  / |/ |  /  |
  |  \\_/ \\_/|/|__/|__/   |(__/|_/  |  |_/\\_/|/
           /|                              /|
           \\|                              \\|

Your project contains lock files generated by tools other than Yarn.
It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.

[1/4] Resolving packages...

ready:    [ ============================================================================== 100% ]
compile:  [ ============================================================================== 100% ]
finished: [ ============================================================================== 100% ]

        > webpack
        > watchpack
        > watchpack-chokidar2
        > chokidar
        > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries.

[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done

`
const offset = ref(0) // 当前显示代码的位置
const step = ref(2) // 一次移动几个字符
const intervalHandle = ref<NodeJS.Timeout | null>(null)
const interval = ref(60) // ms

// Methods
const clearInterval = () => {
    if (intervalHandle.value) clearInterval(intervalHandle.value)
}

// Lifecycle hooks
onMounted(() => {
    intervalHandle.value = setInterval(() => {
        if (showingCode.value === codeOrigin) {
            showingCode.value = ''
            offset.value = 0
            // clearInterval()
        } else {
            showingCode.value = codeOrigin.substring(0, offset.value)
            offset.value = offset.value + step.value
        }
    }, interval.value)
})

onUnmounted(() => {
    clearInterval()
})
</script>

<style scoped lang="scss">
@import "../assets/scss/plugin";
.code{
    white-space: break-spaces;
    color: white;
    font-weight: bold;
    height: 600px;
}

</style>
